name: 🚀 Build & Deploy Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout source code
        uses: actions/checkout@v3

      - name: 🔐 Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 🏗️ Build and Push Docker Image
        run: |
          docker build \
            --build-arg ADAFRUIT_USERNAME=${{ secrets.ADAFRUIT_USERNAME }} \
            --build-arg ADAFRUIT_KEY=${{ secrets.ADAFRUIT_KEY }} \
            --build-arg MONGODB_URI=${{ secrets.MONGODB_URI }} \
            --build-arg MAIL_USERNAME=${{ secrets.MAIL_USERNAME }} \
            --build-arg MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }} \
            --build-arg ADMIN_USERNAME=${{ secrets.ADMIN_USERNAME }} \
            --build-arg ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }} \
            --build-arg JWT_SECRET=${{ secrets.JWT_SECRET }} \
            -t lemonhv/yolofarm:latest .

          docker push lemonhv/yolofarm:latest

      - name: 🔁 Trigger Azure redeploy (Webhook)
        run: |
          curl -X POST ${{ secrets.AZURE_WEBHOOK_URL }}
